package coolerInterfaces;

/**
 * g191210379 - 21b
 * @author Sırrı Can KÖMÜR
 */


import business.Concrete.ActuatorManager;
import business.Concrete.CentralProcessorUnitManager;
import business.Concrete.CoolerManager;
import business.Concrete.InternetUserManager;
import business.Concrete.TemperatureSensorManager;
import business.exception.RecordNotFoundException;
import business.exception.UniqueEntityException;
import business.observer.InternetUserObserver;
import entity.Concrete.Cooler;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import entity.Concrete.Actuator;
import entity.Concrete.CentralProcessorUnit;
import entity.Concrete.InternetUser;
import entity.Concrete.TemperatureSensor;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.concurrent.TimeUnit;
public class FrmNetworkInterface extends javax.swing.JFrame {
    
    
    InternetUser internetUser;
    Cooler cooler;
    CentralProcessorUnit centralProcessorUnit;
    Actuator actuator;
    TemperatureSensor temperatureSensor;
    InternetUserManager internetUserManager;
    InternetUserObserver internetUserObserver;
    CoolerManager coolerManager;
    ActuatorManager actuatorManager;
    CentralProcessorUnitManager centralProcessorUnitManager;
    TemperatureSensorManager temperatureSensorManager;
    
    String instantWorkingStatus;
    int mousePositionX;
    int mousePositionY;
    
    
    public FrmNetworkInterface() {
        initComponents();
        this.setSize(900,550);
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/picture/coolerLogo_32.png")));
        pnlStatusIndicator.setBackground(new java.awt.Color(156,0,0));
        
        internetUserManager = InternetUserManager.createAsSingleton();
        internetUserObserver = new InternetUserObserver();
        internetUserManager.attach(internetUserObserver);
        lblUserInfo.setText(internetUserManager.signedCooler(internetUserObserver));
        lblUserInfo2.setText(internetUserManager.updateCooler());
        
        coolerManager = CoolerManager.createAsSingleton();
        actuator = new Actuator(0, 0, null);
        centralProcessorUnit = new CentralProcessorUnit(0, 0, null);
        
        temperatureSensorManager = TemperatureSensorManager.createAsSingleton();
        String productId = coolerManager.whatProductOfUser(internetUserManager.whoIsActive());
        
        try {
            internetUser = new InternetUser(0, 0, null, null, internetUserManager.whoIsActive(), null, null, "Yes");
            internetUser.setFirstName(internetUserManager.queryFirstName(internetUser));
            internetUser.setLastName(internetUserManager.queryLastName(internetUser));
            
            temperatureSensor = new TemperatureSensor(0, 0, 0, null);
            temperatureSensor.setId(coolerManager.queryTemperatureSensorId(productId));
            temperatureSensorManager.queryLastTemperatureValue(temperatureSensor);
            
            instantWorkingStatus = coolerManager.queryStatusOfCooler(productId);
            centralProcessorUnit.setId(coolerManager.queryCentralProcessorUnitId(productId));
            actuator.setId(coolerManager.queryAcuatorId(productId));
            
            cooler = new Cooler(0, productId, centralProcessorUnit.getId(), actuator.getId(), temperatureSensor.getId(), instantWorkingStatus);
        } catch (RecordNotFoundException ex) {
            Logger.getLogger(FrmNetworkInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UniqueEntityException ex) {
            Logger.getLogger(FrmNetworkInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        lblWelcomeName.setText("Welcome, " + internetUser.getFirstName() + " " + internetUser.getLastName());
        lblProductIdInfo.setText(cooler.getProductId());
        lblInstantStatus.setText(cooler.getInstantWorkingStatus());
        
        if(cooler.getInstantWorkingStatus().equals("Open")){
            pnlInstantStatus.setBackground(new Color(0, 153, 41));
            pnlStatusIndicator.setBackground(new Color(0, 153, 41));
        }else if(cooler.getInstantWorkingStatus().equals("Closed")){
            pnlInstantStatus.setBackground(new Color(156, 0, 0));
            pnlStatusIndicator.setBackground(new Color(156, 0, 0));
        }else if(cooler.getInstantWorkingStatus().equals("Sleep")){
            pnlInstantStatus.setBackground(new Color(227, 185, 0));
            pnlStatusIndicator.setBackground(new Color(227, 185, 0));
        }
        internetUserManager.update(internetUser);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lineDragInterface = new javax.swing.JPanel();
        lblWelcomeName = new javax.swing.JLabel();
        btnExitInterface = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JLabel();
        btnMinimizeInterface = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlCoolerInterfaceLogo = new javax.swing.JPanel();
        lblCoolerInterfaceLogo = new javax.swing.JLabel();
        pnlLogoTurn = new javax.swing.JPanel();
        logoTurn = new javax.swing.JLabel();
        pnlShowTemperature = new javax.swing.JPanel();
        btnShowTemperature = new javax.swing.JLabel();
        pnlInstantWorkingStatus = new javax.swing.JPanel();
        btnInstantWorkingStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlStatusIndicator = new javax.swing.JPanel();
        pnlSleep = new javax.swing.JPanel();
        btnSleep = new javax.swing.JLabel();
        pnlTurnOn = new javax.swing.JPanel();
        btnTurnOn = new javax.swing.JLabel();
        pnlTurnOff = new javax.swing.JPanel();
        btnTurnOff = new javax.swing.JLabel();
        lblProductIdLogo = new javax.swing.JLabel();
        pnlInstantStatus = new javax.swing.JPanel();
        lblInstantStatus = new javax.swing.JLabel();
        lblProductIdInfo = new javax.swing.JLabel();
        pnlTemperatureValue = new javax.swing.JPanel();
        lblTemperatureValue = new javax.swing.JLabel();
        lblTemperatureLogo = new javax.swing.JLabel();
        lblUserInfo = new javax.swing.JLabel();
        lblUserInfo2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lineDragInterface.setBackground(new java.awt.Color(0, 18, 46));
        lineDragInterface.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lineDragInterfaceMouseDragged(evt);
            }
        });
        lineDragInterface.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lineDragInterfaceMousePressed(evt);
            }
        });

        lblWelcomeName.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblWelcomeName.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeName.setText("Welcome");

        btnExitInterface.setForeground(new java.awt.Color(255, 255, 255));
        btnExitInterface.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExitInterface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exitLogo.png"))); // NOI18N
        btnExitInterface.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitInterface.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitInterfaceMouseClicked(evt);
            }
        });

        btnSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/logOut.png"))); // NOI18N
        btnSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignOutMouseClicked(evt);
            }
        });

        btnMinimizeInterface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/minimizeLogo.png"))); // NOI18N
        btnMinimizeInterface.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizeInterface.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeInterfaceMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sign out");

        javax.swing.GroupLayout lineDragInterfaceLayout = new javax.swing.GroupLayout(lineDragInterface);
        lineDragInterface.setLayout(lineDragInterfaceLayout);
        lineDragInterfaceLayout.setHorizontalGroup(
            lineDragInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lineDragInterfaceLayout.createSequentialGroup()
                .addComponent(lblWelcomeName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(btnSignOut)
                .addGap(15, 15, 15)
                .addComponent(btnMinimizeInterface)
                .addGap(15, 15, 15)
                .addComponent(btnExitInterface)
                .addGap(10, 10, 10))
        );
        lineDragInterfaceLayout.setVerticalGroup(
            lineDragInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSignOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinimizeInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lineDragInterfaceLayout.createSequentialGroup()
                .addComponent(btnExitInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblWelcomeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(22, 48, 87));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 470));

        jPanel3.setBackground(new java.awt.Color(0, 18, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(950, 500));

        pnlCoolerInterfaceLogo.setBackground(new java.awt.Color(0, 34, 87));
        pnlCoolerInterfaceLogo.setPreferredSize(new java.awt.Dimension(325, 80));

        lblCoolerInterfaceLogo.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        lblCoolerInterfaceLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblCoolerInterfaceLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoolerInterfaceLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/interfaceCoolerLogo.png"))); // NOI18N
        lblCoolerInterfaceLogo.setText("COOLER INTERFACE");
        lblCoolerInterfaceLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCoolerInterfaceLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCoolerInterfaceLogoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlCoolerInterfaceLogoLayout = new javax.swing.GroupLayout(pnlCoolerInterfaceLogo);
        pnlCoolerInterfaceLogo.setLayout(pnlCoolerInterfaceLogoLayout);
        pnlCoolerInterfaceLogoLayout.setHorizontalGroup(
            pnlCoolerInterfaceLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCoolerInterfaceLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCoolerInterfaceLogoLayout.setVerticalGroup(
            pnlCoolerInterfaceLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCoolerInterfaceLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        pnlLogoTurn.setBackground(new java.awt.Color(0, 23, 59));
        pnlLogoTurn.setPreferredSize(new java.awt.Dimension(325, 180));

        logoTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoTurn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/turnOnOffLogo.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoTurnLayout = new javax.swing.GroupLayout(pnlLogoTurn);
        pnlLogoTurn.setLayout(pnlLogoTurnLayout);
        pnlLogoTurnLayout.setHorizontalGroup(
            pnlLogoTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLogoTurnLayout.setVerticalGroup(
            pnlLogoTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoTurn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlShowTemperature.setBackground(new java.awt.Color(0, 23, 59));
        pnlShowTemperature.setPreferredSize(new java.awt.Dimension(325, 180));

        btnShowTemperature.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnShowTemperature.setForeground(new java.awt.Color(255, 255, 255));
        btnShowTemperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShowTemperature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/showTemperatureLogo.png"))); // NOI18N
        btnShowTemperature.setText("Show Temperature");
        btnShowTemperature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowTemperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowTemperatureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShowTemperatureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShowTemperatureMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlShowTemperatureLayout = new javax.swing.GroupLayout(pnlShowTemperature);
        pnlShowTemperature.setLayout(pnlShowTemperatureLayout);
        pnlShowTemperatureLayout.setHorizontalGroup(
            pnlShowTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnShowTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlShowTemperatureLayout.setVerticalGroup(
            pnlShowTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnShowTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        pnlInstantWorkingStatus.setBackground(new java.awt.Color(0, 23, 59));
        pnlInstantWorkingStatus.setPreferredSize(new java.awt.Dimension(325, 180));

        btnInstantWorkingStatus.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnInstantWorkingStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnInstantWorkingStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInstantWorkingStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/instantWorkingStatus.png"))); // NOI18N
        btnInstantWorkingStatus.setText("Instant Working Status");
        btnInstantWorkingStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInstantWorkingStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInstantWorkingStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInstantWorkingStatusMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlInstantWorkingStatusLayout = new javax.swing.GroupLayout(pnlInstantWorkingStatus);
        pnlInstantWorkingStatus.setLayout(pnlInstantWorkingStatusLayout);
        pnlInstantWorkingStatusLayout.setHorizontalGroup(
            pnlInstantWorkingStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInstantWorkingStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        pnlInstantWorkingStatusLayout.setVerticalGroup(
            pnlInstantWorkingStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInstantWorkingStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        pnlStatusIndicator.setBackground(new java.awt.Color(156, 0, 0));
        pnlStatusIndicator.setForeground(new java.awt.Color(153, 0, 0));
        pnlStatusIndicator.setPreferredSize(new java.awt.Dimension(325, 6));

        javax.swing.GroupLayout pnlStatusIndicatorLayout = new javax.swing.GroupLayout(pnlStatusIndicator);
        pnlStatusIndicator.setLayout(pnlStatusIndicatorLayout);
        pnlStatusIndicatorLayout.setHorizontalGroup(
            pnlStatusIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlStatusIndicatorLayout.setVerticalGroup(
            pnlStatusIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        pnlSleep.setBackground(new java.awt.Color(0, 23, 59));
        pnlSleep.setPreferredSize(new java.awt.Dimension(325, 180));

        btnSleep.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnSleep.setForeground(new java.awt.Color(255, 255, 255));
        btnSleep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sleepLogo.png"))); // NOI18N
        btnSleep.setText("Sleep");
        btnSleep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSleep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSleepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSleepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSleepMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSleepLayout = new javax.swing.GroupLayout(pnlSleep);
        pnlSleep.setLayout(pnlSleepLayout);
        pnlSleepLayout.setHorizontalGroup(
            pnlSleepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSleep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSleepLayout.setVerticalGroup(
            pnlSleepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSleep, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        pnlTurnOn.setBackground(new java.awt.Color(0, 23, 59));
        pnlTurnOn.setPreferredSize(new java.awt.Dimension(325, 180));

        btnTurnOn.setBackground(new java.awt.Color(51, 153, 0));
        btnTurnOn.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnTurnOn.setForeground(new java.awt.Color(255, 255, 255));
        btnTurnOn.setText("Turn On");
        btnTurnOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTurnOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTurnOnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTurnOnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTurnOnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTurnOnLayout = new javax.swing.GroupLayout(pnlTurnOn);
        pnlTurnOn.setLayout(pnlTurnOnLayout);
        pnlTurnOnLayout.setHorizontalGroup(
            pnlTurnOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTurnOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTurnOnLayout.setVerticalGroup(
            pnlTurnOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTurnOnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTurnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTurnOff.setBackground(new java.awt.Color(0, 23, 59));
        pnlTurnOff.setPreferredSize(new java.awt.Dimension(325, 180));

        btnTurnOff.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnTurnOff.setForeground(new java.awt.Color(255, 255, 255));
        btnTurnOff.setText("Turn Off");
        btnTurnOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTurnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTurnOffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTurnOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTurnOffMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTurnOffLayout = new javax.swing.GroupLayout(pnlTurnOff);
        pnlTurnOff.setLayout(pnlTurnOffLayout);
        pnlTurnOffLayout.setHorizontalGroup(
            pnlTurnOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTurnOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTurnOffLayout.setVerticalGroup(
            pnlTurnOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTurnOffLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTurnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pnlLogoTurn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTurnOff, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(pnlTurnOn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
            .addComponent(pnlCoolerInterfaceLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(pnlInstantWorkingStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(pnlStatusIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(pnlSleep, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(pnlShowTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pnlCoolerInterfaceLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlInstantWorkingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlStatusIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLogoTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnlTurnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlTurnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(pnlSleep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlShowTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        lblProductIdLogo.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblProductIdLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblProductIdLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/productLogo.png"))); // NOI18N
        lblProductIdLogo.setText("PRODUCT ID:");

        pnlInstantStatus.setBackground(new java.awt.Color(156, 0, 0));
        pnlInstantStatus.setPreferredSize(new java.awt.Dimension(100, 85));

        lblInstantStatus.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblInstantStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblInstantStatus.setText(" ");

        javax.swing.GroupLayout pnlInstantStatusLayout = new javax.swing.GroupLayout(pnlInstantStatus);
        pnlInstantStatus.setLayout(pnlInstantStatusLayout);
        pnlInstantStatusLayout.setHorizontalGroup(
            pnlInstantStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInstantStatusLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInstantStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInstantStatusLayout.setVerticalGroup(
            pnlInstantStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInstantStatusLayout.createSequentialGroup()
                .addComponent(lblInstantStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        lblProductIdInfo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblProductIdInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblProductIdInfo.setText(" ");
        lblProductIdInfo.setToolTipText("");

        pnlTemperatureValue.setBackground(new java.awt.Color(22, 48, 87));

        lblTemperatureValue.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblTemperatureValue.setForeground(new java.awt.Color(255, 255, 255));
        lblTemperatureValue.setText(" ");

        lblTemperatureLogo.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblTemperatureLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblTemperatureLogo.setText(" ");

        javax.swing.GroupLayout pnlTemperatureValueLayout = new javax.swing.GroupLayout(pnlTemperatureValue);
        pnlTemperatureValue.setLayout(pnlTemperatureValueLayout);
        pnlTemperatureValueLayout.setHorizontalGroup(
            pnlTemperatureValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTemperatureValueLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTemperatureLogo)
                .addGap(5, 5, 5)
                .addComponent(lblTemperatureValue, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTemperatureValueLayout.setVerticalGroup(
            pnlTemperatureValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTemperatureValue, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
            .addComponent(lblTemperatureLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblUserInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblUserInfo.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        lblUserInfo.setForeground(new java.awt.Color(204, 204, 204));
        lblUserInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserInfo.setText(" ");

        lblUserInfo2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        lblUserInfo2.setForeground(new java.awt.Color(255, 255, 255));
        lblUserInfo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserInfo2.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblProductIdLogo)
                        .addGap(18, 18, 18)
                        .addComponent(lblProductIdInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlInstantStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(pnlTemperatureValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserInfo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProductIdLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(lblProductIdInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(pnlInstantStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTemperatureValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUserInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lineDragInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lineDragInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnExitInterfaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitInterfaceMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitInterfaceMouseClicked
    
    private void btnMinimizeInterfaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeInterfaceMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeInterfaceMouseClicked
    
    private void btnSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOutMouseClicked
        actuatorManager = ActuatorManager.createAsSingleton();
        centralProcessorUnitManager = CentralProcessorUnitManager.createAsSingleton();
        coolerManager = CoolerManager.createAsSingleton();
        temperatureSensorManager = TemperatureSensorManager.createAsSingleton();
        
        cooler.setInstantWorkingStatus("Closed");
        actuatorManager.turnOffActuator(cooler);
        centralProcessorUnitManager.turnOffCentralProcessorUnit(cooler);
        coolerManager.updateInstantWorkingStatus(cooler);
        
        internetUser.setIsActive("No");
        internetUserManager.update(internetUser);
        
        temperatureSensor.setIsActive("No");
        temperatureSensorManager.update(temperatureSensor);
        
        FrmSignInInterface signInInterface = new FrmSignInInterface();
        signInInterface.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSignOutMouseClicked
    
    private void btnTurnOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOnMouseClicked
        actuatorManager = ActuatorManager.createAsSingleton();
        centralProcessorUnitManager = CentralProcessorUnitManager.createAsSingleton();
        coolerManager = CoolerManager.createAsSingleton();
        
        cooler.setInstantWorkingStatus("Open");
        actuatorManager.turnOnActuator(cooler);
        centralProcessorUnitManager.turnOnCentralProcessorUnit(cooler);
        coolerManager.updateInstantWorkingStatus(cooler);
        
        lblInstantStatus.setText(cooler.getInstantWorkingStatus());
        pnlInstantStatus.setBackground(new Color(0, 153, 41));
        pnlStatusIndicator.setBackground(new Color(0, 153, 41));
        DecimalFormat decimalFormat = new DecimalFormat();
        decimalFormat.setMaximumFractionDigits(4);
        
        pnlTemperatureValue.setBackground(new Color(168, 95, 0));
        lblTemperatureLogo.setText("Last Temperature:");
        lblTemperatureValue.setText(String.valueOf(decimalFormat.format(temperatureSensor.getMeasuredValue())) + " Degrees Celsius");
        
        try {
            instantWorkingStatus = coolerManager.queryStatusOfCooler(cooler.getProductId());
        } catch (RecordNotFoundException ex) {
            Logger.getLogger(FrmNetworkInterface.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_btnTurnOnMouseClicked
    
    private void btnTurnOnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOnMouseEntered
        pnlTurnOn.setBackground(new java.awt.Color(0, 29, 74));
        pnlLogoTurn.setBackground(new Color(0, 29, 74));
    }//GEN-LAST:event_btnTurnOnMouseEntered
    
    private void btnTurnOnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOnMouseExited
        pnlTurnOn.setBackground(new java.awt.Color(0, 23, 59));
        pnlLogoTurn.setBackground(new Color(0, 23, 59));
    }//GEN-LAST:event_btnTurnOnMouseExited
    
    private void btnShowTemperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowTemperatureMouseClicked
        temperatureSensorManager = TemperatureSensorManager.createAsSingleton();
        coolerManager = CoolerManager.createAsSingleton();
        temperatureSensor.setMeasuredValue(temperatureSensorManager.measureTemperature());
        temperatureSensor.setIsActive("Yes");
        temperatureSensorManager.update(temperatureSensor);
        cooler.setInstantWorkingStatus("Temperature Measurement");
        coolerManager.updateInstantWorkingStatus(cooler);
        lblInstantStatus.setText(cooler.getInstantWorkingStatus());
        pnlInstantStatus.setBackground(new Color(168, 95, 0));
        lblUserInfo.setText(" ");
        try {
            TimeUnit.SECONDS.sleep(2);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmNetworkInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DecimalFormat decimalFormat = new DecimalFormat();
        decimalFormat.setMaximumFractionDigits(4);
        
        pnlTemperatureValue.setBackground(new Color(168, 95, 0));
        lblTemperatureLogo.setText("Temperature:");
        lblTemperatureValue.setText(String.valueOf(decimalFormat.format(temperatureSensor.getMeasuredValue())) + " Degrees Celsius");
        
        cooler.setInstantWorkingStatus("Open");
        lblInstantStatus.setText(cooler.getInstantWorkingStatus());
        coolerManager.updateInstantWorkingStatus(cooler);
        pnlInstantStatus.setBackground(new Color(0, 153, 41));
        pnlStatusIndicator.setBackground(new Color(0, 153, 41));           
    }//GEN-LAST:event_btnShowTemperatureMouseClicked
    
    private void btnShowTemperatureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowTemperatureMouseEntered
        pnlShowTemperature.setBackground(new java.awt.Color(0, 29, 74));
    }//GEN-LAST:event_btnShowTemperatureMouseEntered
    
    private void btnShowTemperatureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowTemperatureMouseExited
        pnlShowTemperature.setBackground(new java.awt.Color(0, 23, 59));
    }//GEN-LAST:event_btnShowTemperatureMouseExited
    
    private void lblCoolerInterfaceLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCoolerInterfaceLogoMouseEntered
        pnlCoolerInterfaceLogo.setBackground(new java.awt.Color(0, 37, 94));
    }//GEN-LAST:event_lblCoolerInterfaceLogoMouseEntered
    
    private void lblCoolerInterfaceLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCoolerInterfaceLogoMouseExited
        pnlCoolerInterfaceLogo.setBackground(new java.awt.Color(0, 34, 87));
    }//GEN-LAST:event_lblCoolerInterfaceLogoMouseExited
    
    private void btnInstantWorkingStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstantWorkingStatusMouseEntered
        pnlInstantWorkingStatus.setBackground(new java.awt.Color(0, 29, 74));
    }//GEN-LAST:event_btnInstantWorkingStatusMouseEntered
    
    private void btnInstantWorkingStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstantWorkingStatusMouseExited
        pnlInstantWorkingStatus.setBackground(new java.awt.Color(0, 23, 59));
    }//GEN-LAST:event_btnInstantWorkingStatusMouseExited
    
    private void lineDragInterfaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineDragInterfaceMousePressed
        mousePositionX = evt.getX();
        mousePositionY = evt.getY();
    }//GEN-LAST:event_lineDragInterfaceMousePressed
    
    private void lineDragInterfaceMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineDragInterfaceMouseDragged
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        
        this.setLocation(coordinateX - mousePositionX, coordinateY - mousePositionY);
    }//GEN-LAST:event_lineDragInterfaceMouseDragged
    
    private void btnSleepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSleepMouseClicked
        centralProcessorUnitManager = CentralProcessorUnitManager.createAsSingleton();
        coolerManager = CoolerManager.createAsSingleton();
        temperatureSensorManager = TemperatureSensorManager.createAsSingleton();
        
        cooler.setInstantWorkingStatus("Sleep");
        centralProcessorUnitManager.sleepOnCooler(cooler);
        coolerManager.updateInstantWorkingStatus(cooler);
        pnlStatusIndicator.setBackground(new Color(227, 185, 0));
        
        lastTemperature();
        
        temperatureSensor.setIsActive("No");
        temperatureSensorManager.update(temperatureSensor);
        
        lblInstantStatus.setText(cooler.getInstantWorkingStatus());
        pnlInstantStatus.setBackground(new Color(227, 185, 0));
        lblUserInfo.setText(" ");
        try {
            instantWorkingStatus = coolerManager.queryStatusOfCooler(cooler.getProductId());
        } catch (RecordNotFoundException ex) {
            Logger.getLogger(FrmNetworkInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSleepMouseClicked
    
    private void btnSleepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSleepMouseEntered
        pnlSleep.setBackground(new java.awt.Color(0, 29, 74));
        
    }//GEN-LAST:event_btnSleepMouseEntered
    
    private void btnSleepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSleepMouseExited
        pnlSleep.setBackground(new java.awt.Color(0, 23, 59));
        
    }//GEN-LAST:event_btnSleepMouseExited
    
    private void btnTurnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOffMouseClicked
        actuatorManager = ActuatorManager.createAsSingleton();
        centralProcessorUnitManager = CentralProcessorUnitManager.createAsSingleton();
        coolerManager = CoolerManager.createAsSingleton();
        temperatureSensorManager = TemperatureSensorManager.createAsSingleton();
        
        cooler.setInstantWorkingStatus("Closed");
        actuatorManager.turnOffActuator(cooler);
        centralProcessorUnitManager.turnOffCentralProcessorUnit(cooler);
        coolerManager.updateInstantWorkingStatus(cooler);
        
        lastTemperature();
        
        temperatureSensor.setIsActive("No");
        temperatureSensorManager.update(temperatureSensor);
        lblUserInfo.setText(" ");
        pnlStatusIndicator.setBackground(new Color(156, 0, 0));
        lblInstantStatus.setText(cooler.getInstantWorkingStatus());
        pnlInstantStatus.setBackground(new Color(156, 0, 0));
        
        try {
            instantWorkingStatus = coolerManager.queryStatusOfCooler(cooler.getProductId());
        } catch (RecordNotFoundException ex) {
            Logger.getLogger(FrmNetworkInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTurnOffMouseClicked
    
    private void btnTurnOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOffMouseEntered
        pnlTurnOff.setBackground(new java.awt.Color(0, 29, 74));
        pnlLogoTurn.setBackground(new Color(0, 29, 74));
    }//GEN-LAST:event_btnTurnOffMouseEntered
    
    private void btnTurnOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOffMouseExited
        pnlTurnOff.setBackground(new java.awt.Color(0, 23, 59));
        pnlLogoTurn.setBackground(new Color(0, 23, 59));
    }//GEN-LAST:event_btnTurnOffMouseExited
    
    private void lastTemperature(){
        DecimalFormat decimalFormat = new DecimalFormat();
        decimalFormat.setMaximumFractionDigits(4);
        
        pnlTemperatureValue.setBackground(new Color(168, 95, 0));
        lblTemperatureLogo.setText("Last Temperature:");
        lblTemperatureValue.setText(String.valueOf(decimalFormat.format(temperatureSensor.getMeasuredValue())) + " Degrees Celsius");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNetworkInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNetworkInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNetworkInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNetworkInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNetworkInterface().setVisible(true);
                
            }
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExitInterface;
    private javax.swing.JLabel btnInstantWorkingStatus;
    private javax.swing.JLabel btnMinimizeInterface;
    private javax.swing.JLabel btnShowTemperature;
    private javax.swing.JLabel btnSignOut;
    private javax.swing.JLabel btnSleep;
    private javax.swing.JLabel btnTurnOff;
    private javax.swing.JLabel btnTurnOn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCoolerInterfaceLogo;
    private javax.swing.JLabel lblInstantStatus;
    private javax.swing.JLabel lblProductIdInfo;
    private javax.swing.JLabel lblProductIdLogo;
    private javax.swing.JLabel lblTemperatureLogo;
    private javax.swing.JLabel lblTemperatureValue;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JLabel lblUserInfo2;
    private javax.swing.JLabel lblWelcomeName;
    private javax.swing.JPanel lineDragInterface;
    private javax.swing.JLabel logoTurn;
    private javax.swing.JPanel pnlCoolerInterfaceLogo;
    private javax.swing.JPanel pnlInstantStatus;
    private javax.swing.JPanel pnlInstantWorkingStatus;
    private javax.swing.JPanel pnlLogoTurn;
    private javax.swing.JPanel pnlShowTemperature;
    private javax.swing.JPanel pnlSleep;
    private javax.swing.JPanel pnlStatusIndicator;
    private javax.swing.JPanel pnlTemperatureValue;
    private javax.swing.JPanel pnlTurnOff;
    private javax.swing.JPanel pnlTurnOn;
    // End of variables declaration//GEN-END:variables
}
